#!/usr/bin/env bash

# a placeholder for training script which will be called by Sagemaker at training time

cd /opt/ml/code/detectron2/tools
python ./train_net.py --num-gpus 1 --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml